# Use root/example as user/password credentials
version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    restart: always
    ports:
      - 15184:15184
    depends_on:
      - mongo

